name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Print event
        shell: bash
        run: echo Event ${{ github.event }}
    
      - name: List files
        shell: bash
        run: ls -la
        
      - name: Buka
        shell: bash
        run: echo "buka" >> buka.txt
      
      - name: Checkout
        uses: actions/checkout@master
        
      - name: List files
        shell: bash
        run: ls -la

  deploy-test:
    runs-on: 'ubuntu-latest'
    environment: 'test'
    needs: build-and-publish
    steps:
      - name: Download artifact
        run: ls -la

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [build-and-publish, deploy-test]
    steps:
      - name: Download artifact
        run: ls -la
